"""jobs_part1.py - the part-1 picture jobs, in order of first encounter (boot -> notices -> title -> navigator -> scene).

Each job: id, screen, style (font parameter by style name; see batch.py FONTS), items = the pictures that share the
layout (normal / hover / greyed variants), one English string per item (or per word for `words` / `match` jobs),
erase method, and optional overrides. `wording` names where the English already existed; jobs marked new=True are
first translations and are logged to notes/_tmp/tl-log-IMAGES.md by batch.py.
Archive paths use forward slashes here; batch.py maps them to work/images/png (source), work/images/gal (template),
work/グラフィック/... (shipped .gal) and F:/4gatsu_8ka_EN/グラフィック/... (loose file).
"""

T = "グラフィック/タイトル/"
S = "グラフィック/システム/"
N = "グラフィック/シナリオナビ/"

WARNINGS = [  # the 19 content-warning words (brush, display words -> ALL CAPS per the owner's rule)
    ("児童惨殺", "CHILD MURDER"), ("薬物", "DRUGS"), ("触手", "TENTACLES"), ("死体", "CORPSES"),
    ("カニバリズム", "CANNIBALISM"), ("殺人", "MURDER"), ("虫", "INSECTS"), ("いじめ", "BULLYING"),
    ("死姦", "NECROPHILIA"), ("監禁", "CONFINEMENT"), ("血", "BLOOD"), ("暴力", "VIOLENCE"),
    ("人体実験", "HUMAN EXPERIMENTS"), ("内臓", "ENTRAILS"), ("人体欠損", "DISMEMBERMENT"),
    ("怪異", "APPARITIONS"), ("下ネタ", "DIRTY JOKES"), ("脅かし", "JUMP SCARES"),
]

JOBS = [
    # ---- boot: notice gate ------------------------------------------------------------------------------------
    dict(id="notice-consent", screen="boot notice gate", style="gothic", erase="flat",
         items=[(T + "了承する.gal", "I consent"), (T + "了承しない.gal", "I do not consent")],
         wording="tsv-en/注意.tsv (consent)"),
    dict(id="notice-wallpaper-reading", screen="boot notice gate (wallpaper)", style="gothic",
         erase="inpaint", box=[430, 28, 900, 59], mask_color=[140, 255, 0, 90, 0, 90], textbox=[445, 31, 885, 58],
         color="#e40000", stroke=1, stroke_color="#7a0000", spacing=8,
         items=[(S + "壁紙.gal", "SHIGATSU YOUKA")], wording="demo (reading of the title)", new=True,
         note="the kana reading above the logo, as a Latin reading line"),
    # ---- notices: content warnings (the .lcm animates the 19 singles over the composite) ------------------------
    # Colours sampled from the originals with tools/images/warn_colors.py (2026-09-26): every word is drawn in
    # one flat colour with NO outline - 17 of them red (core 251,2,2) and 下ネタ pink (core 254,152,254). The
    # first pass let the analyser pick a colour AND add a 1 px white stroke, which lightened every word
    # (mean 253,145,145 against the original 234,9,9) and turned the pink one red.
    dict(id="notice-warnings-singles", screen="content-warning notice", style="brush", erase="alpha", caps=True,
         color="#fb0202", stroke=0,
         items=[(T + "残酷/" + jp + ".gal", en) if jp != "下ネタ" else
                (T + "残酷/" + jp + ".gal", en, {"color": "#fe98fe"}) for jp, en in WARNINGS],
         new=True,
         note="display words -> ALL CAPS; 内臓 = ENTRAILS, 怪異 = APPARITIONS, 脅かし = JUMP SCARES, 下ネタ = DIRTY JOKES are judgment calls (Q2001-Q2004)"),
    dict(id="notice-warnings-composite", screen="content-warning notice", style="brush", erase="inpaint", caps=True,
         mode="boxes", color="#f90202", stroke=0, items=[(T + "残酷/残酷.gal", None)], new=True,
         boxes=[  # (English, box in the 960x540 composite) read off the picture; the composite says 児童虐待 (abuse)
             ("CHILD ABUSE", [8, 22, 276, 95]), ("DRUGS", [612, 47, 746, 110]), ("TENTACLES", [802, 37, 936, 110]),
             ("CORPSES", [72, 142, 196, 210]), ("CANNIBALISM", [216, 102, 642, 175]), ("MURDER", [656, 152, 782, 225]),
             ("INSECTS", [810, 132, 882, 200]), ("BULLYING", [306, 202, 522, 270]), ("NECROPHILIA", [806, 242, 932, 305]),
             ("CONFINEMENT", [36, 282, 162, 345]), ("HUMAN EXPERIMENTS", [530, 282, 802, 360]), ("BLOOD", [226, 327, 292, 380]),
             ("VIOLENCE", [336, 327, 476, 400]), ("ENTRAILS", [810, 337, 942, 410]), ("DISMEMBERMENT", [2, 432, 292, 520]),
             ("APPARITIONS", [298, 458, 456, 520]), ("DIRTY JOKES", [458, 452, 680, 520], "#fe98fe"), ("JUMP SCARES", [760, 442, 946, 520])],
         protect=[[684, 470, 748, 540]],
         note="each word erased (red mask inside its box, inpainted) and re-set in its own box; the pink heart stays"),
    dict(id="notice-guide-nameplate", screen="notices (guide name plate)", style="serif", erase="flat",
         items=[(S + "立木三日プレート.gal", "Mikka Tachiki")], wording="GLOSSARY.tsv (Mikka Tachiki, provisional)",
         note="furigana line dropped"),
    # ---- title menu ---------------------------------------------------------------------------------------------
    dict(id="title-menu", screen="title menu", style="brush", erase="inpaint", caps=True,
         items=[(T + "開始.gal", "START"), (T + "雑談.gal", "CHATTER"), (T + "雑談黒.gal", "CHATTER"),
                (T + "事典.gal", "ENCYCLOPEDIA"), (T + "事典黒.gal", "ENCYCLOPEDIA"),
                (T + "ドキュメント.gal", "DOCUMENTS"), (T + "ドキュメント黒.gal", "DOCUMENTS"),
                (T + "リファレンス.gal", "REFERENCES"), (T + "リファレンス黒.gal", "REFERENCES")],
         wording="tsv-en/チュートリアル.tsv (chatter, encyclopedia, references, document mode)"),
    dict(id="title-menu-load", screen="title menu", style="brush", erase="inpaint", caps=False,
         items=[(T + "中断.gal", "Load break-off data"), (T + "中断黒.gal", "Load break-off data")],
         wording="patch/labels-0000001E.tsv (break-off data)", note="sentence-like -> mixed case"),
    # ---- scenario navigator, first view --------------------------------------------------------------------------
    dict(id="nav-start-scenario", screen="navigator", style="serif", erase="flat",
         items=[(N + "このシナリオを開始.gal", "Start this scenario"), (N + "このシナリオを開始s.gal", "Start this scenario")],
         wording="patch/labels-0000001C.tsv (Will you start this scenario?)"),
    dict(id="nav-start", screen="navigator", style="serif", erase="flat",
         items=[(N + "開始.gal", "Start"), (N + "開始s.gal", "Start")], wording="labels-0000001C"),
    dict(id="nav-from-beginning", screen="navigator", style="serif", erase="flat",
         items=[(N + "最初から.gal", "From the beginning"), (N + "最初からs.gal", "From the beginning")],
         wording="tsv-en/注意.tsv (Start over from the beginning)"),
    dict(id="nav-from-branch", screen="navigator", style="serif", erase="flat",
         items=[(N + "分岐直前から.gal", "From just before\nthe branch"), (N + "分岐直前からs.gal", "From just before\nthe branch"),
                (N + "分岐直前から灰.gal", "From just before\nthe branch")],
         wording="labels-0000001C (branch)", new=True),
    dict(id="nav-from-lock", screen="navigator", style="serif", erase="flat",
         items=[(N + "ロック直前から.gal", "From just before\nthe lock"), (N + "ロック直前からs.gal", "From just before\nthe lock")],
         new=True),
    dict(id="nav-routes", screen="navigator", style="serif", erase="flat",
         items=[(N + "ルート1.gal", "Old route"), (N + "ルート1s.gal", "Old route"),
                (N + "ルート2.gal", "New route"), (N + "ルート2s.gal", "New route")],
         wording="labels-0000001C (route)", new=True),
    dict(id="nav-confirm", screen="navigator", style="serif", erase="flat",
         items=[(N + "確認.gal", "Confirm"), (N + "確認s.gal", "Confirm")], new=True),
    dict(id="nav-cancel", screen="navigator", style="serif", erase="flat",
         items=[(N + "キャンセル.gal", "Cancel"), (N + "キャンセルｓ.gal", "Cancel")],
         wording="tsv-en/チュートリアル.tsv (All Cancel)"),
    dict(id="nav-after-load", screen="navigator (after a load)", style="serif", erase="flat",
         items=[(N + "ロード後.gal", "Left-click or press Enter.")], new=True),
    dict(id="nav-reference-header", screen="navigator (reference panel header)", style="gothic", erase="flat",
         items=[(N + "タイトル.gal", "References")], wording="tsv-en/チュートリアル.tsv (the references)"),
    dict(id="nav-chatter-updated", screen="navigator (banner)", style="gothic", erase="inpaint",
         mask_color=[150, 255, 150, 255, 150, 255], color="#ffffff", stroke=1, stroke_color="#1a0a2a",
         items=[(N + "雑談解禁.gal", "Chatter updated"), (N + "雑談解禁2.gal", "Chatter updated")],
         wording="tsv-en/チュートリアル.tsv (chatter)", new=True),
    dict(id="nav-hidden-route", screen="navigator (synopsis window)", style="serif", erase="flat",
         box=[6, 6, 108, 42], keep_edges=True,
         items=[(S + "裏ルートへ.gal", "Hidden route"), (S + "裏ルートへ2.gal", "Hidden route 2"),
                (S + "裏ルートへ3.gal", "Hidden route 3"), (S + "裏ルートへ4.gal", "Hidden route 4")],
         wording="labels-0000001C (hidden route 2/3/4)"),
    dict(id="nav-tags", screen="navigator (node tags)", style="gothic", erase="flat", pad=1,
         items=[(N + "実況.gal", "CMT"), (N + "実況2.gal", "CMT"), (N + "中断.gal", "BRK"),
                (N + "分岐.gal", "BR"), (N + "分岐2.gal", "BR")],
         new=True, note="tiny node tags (20-40 px): CMT = commentary mode, BRK = break-off data, BR = branch, HR = hidden route (Q2005); 分岐1 is an icon without text"),
    dict(id="nav-tags-hidden", screen="navigator (node tags)", style="gothic", erase="inpaint", pad=1, keep_edges=True,
         mask_color=[170, 255, 170, 255, 170, 255], color="#ffffff", stroke=1, stroke_color="#000000",
         items=[(N + "裏.gal", "HR"),
                (N + "裏2.gal", "HR", {"mask_color": [80, 255, 0, 90, 0, 90], "color": "#a00000", "stroke": 0}),
                (N + "裏分岐.gal", "HBR"), (N + "裏分岐2.gal", "HBR")],
         new=True, note="white lettering on coloured blocks: white mask, inpaint, white text with a black outline"),
    # ---- inside the first scene ----------------------------------------------------------------------------------
    dict(id="scene-menubar", screen="scene (pull-out menu bar)", style="gothic", erase="flat", mode="words",
         items=[(S + "メニューバー.gal", None), (S + "メニューバー黒.gal", None)],
         words=["Save", "Load", "Skip", "Hide", "Options"],
         word_boxes=[[28, 4, 110, 36], [112, 4, 192, 36], [194, 4, 294, 36], [56, 42, 148, 78], [150, 42, 284, 78]],
         wording="tsv-en/チュートリアル.tsv (save, load, skip, hides the text, options)",
         note="each word is re-set in its own place so the click areas still line up"),
    dict(id="scene-ref-prompt", screen="scene (reference prompt bar)", style="serif", erase="flat", lines=2,
         items=[(S + "リファレンス見る見ない.gal", "View the reference you obtained now?\n(After viewing, the scenario resumes right where it left off.)"),
                (S + "リファレンス見る見ない末端.gal", "View the reference you obtained now?\n(After viewing, the scenario resumes right where it left off.)"),
                (S + "リファレンス見る見ないテキスト.gal", "View the reference you just obtained?\n(You will return here right after viewing.)")],
         new=True),
    dict(id="scene-ref-buttons", screen="scene (reference prompt buttons)", style="gothic", erase="flat",
         items=[(S + "リファレンス見る.gal", "View"), (S + "リファレンス見るs.gal", "View"),
                (S + "リファレンス見ない.gal", "Not now"), (S + "リファレンス見ないs.gal", "Not now")], new=True),
    dict(id="scene-log-overlay", screen="scene (log overlay)", style="gothic", erase="alpha", lines=2, stroke=2,
         items=[(S + "ログ表示中.gal", "Viewing the log\nRight-click to close")], new=True),
    dict(id="scene-yes-no", screen="scene prompts", style="brush", erase="inpaint", caps=False,
         stroke=0,
         items=[(S + "はい.gal", "Yes", {"color": "#7a1414"}), (S + "はいs.gal", "Yes", {"color": "#942724"}),
                (S + "はい黒.gal", "Yes", {"color": "#0b0b0b"}),
                (S + "いいえ.gal", "No", {"color": "#7a1414"}), (S + "いいえs.gal", "No", {"color": "#942724"})],
         wording="tsv-en/注意.tsv (Yes / No)",
         note="answer words, not display words -> mixed case; the originals are faint brush marks, so the fill is set explicitly (dark red / hover red / black) for legibility"),
    dict(id="scene-help", screen="scene / chatter (help icon)", style="rounded", erase="inpaint",
         mask_color=[170, 255, 140, 255, 0, 120],
         items=[(S + "ヘルプ.gal", "Help"), (S + "ヘルプs.gal", "Help")], new=True),
    dict(id="scene-end-menu", screen="scene end", style="rounded", erase="inpaint", lines=2,
         items=[(S + "シナリオ終わり/終わりあらすじ.gal", "This scenario's\nsynopsis"), (S + "シナリオ終わり/終わりあらすじs.gal", "This scenario's\nsynopsis"),
                (S + "シナリオ終わり/終わりルートあらすじボタン.gal", "This route's\nsynopsis"), (S + "シナリオ終わり/終わりルートあらすじボタンs.gal", "This route's\nsynopsis"),
                (S + "シナリオ終わり/終わりシナリオの続きへ.gal", "Continue the\nscenario"), (S + "シナリオ終わり/終わりシナリオの続きへs.gal", "Continue the\nscenario"),
                (S + "シナリオ終わり/終わりシナリオナビへ.gal", "To the scenario\nnavigator"), (S + "シナリオ終わり/終わりシナリオナビへs.gal", "To the scenario\nnavigator"),
                (S + "シナリオ終わり/終わりリファレンスへ.gal", "To the\nreferences"), (S + "シナリオ終わり/終わりリファレンスへs.gal", "To the\nreferences"),
                (S + "シナリオ終わり/終わり事典へ.gal", "To the\nencyclopedia"), (S + "シナリオ終わり/終わり事典へs.gal", "To the\nencyclopedia")],
         wording="tsv-en/チュートリアル.tsv (synopsis, scenario navigator, references, encyclopedia)", new=True),
    # ---- save / load screen (title menu -> load) -------------------------------------------------------------------
    dict(id="saveload-captions", screen="save/load screen", style="gothic", erase="inpaint",
         mask_color=[170, 255, 170, 255, 170, 255], color="#f4f4f4", stroke=0,
         items=[(S + "セーブロード/セーブタイトル.gal", "Save"), (S + "セーブロード/ロードタイトル.gal", "Load")],
         wording="tsv-en/チュートリアル.tsv"),
    dict(id="saveload-done", screen="save/load screen", style="gothic", erase="flat",
         items=[(S + "セーブロード/完了.gal", "Done"), (S + "セーブロード/完了s.gal", "Done")], new=True),
    dict(id="saveload-empty", screen="save/load screen", style="brush", erase="alpha", caps=True,
         items=[(S + "セーブロード/未使用.gal", "EMPTY")], new=True),
    dict(id="saveload-delete", screen="save/load screen", style="serif", erase="flat",
         items=[(S + "セーブロード/消去.gal", "Delete", {"color": "#f6eeea", "stroke": 0}),
                (S + "セーブロード/消去s.gal", "Delete")], new=True),
]
